#!/usr/bin/env bash
# install nginx on the server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
string_red="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/yantiomene permanent;"
sudo sed -i "s/server_name _;/$string_red/" /etc/nginx/sites-enabled/default

sudo service nginx restart
