#!/usr/bin/env bash
#Dsiplays the content of the file etc/passwd
#+ The script should print only the
#username, user id, and home directory path for the user
while IFS= read -r line
do
	echo "$line" | cut -f 1,3,6 -d ":"
done < "/etc/passwd"
