#!/usr/bin/env bash
#Displays numbers from 1 tp 20 and a specific ms
#+ in case of 4, 9 and 17
i=1
while [ "$i" -le 20 ]
do
	case "$i" in
	     4)
		echo "$i"
		echo "bad luck from China"
		;;
	     9)
		echo "$i"
		echo "bad luck from Japan"
		;;
	     17)
		echo "$i"
		echo "bad luck from Italy"
		;;
	     *)
		echo "$i"
		;;
	esac
	(( i++ ))
done
