#!/usr/bin/env bash
#script to configure an Ubuntu server with IP addresses
cp /etc/hosts ~/hosts.edit
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.edit
sed -i '2i8.8.8.8 facebook.com' ~/hosts.edit
cp ~/hosts.edit /etc/hosts
rm ~/hosts.edit
